/**
 * Go Siargao catalog.
 *
 * The place catalog is now the real, GPS-tagged **General Luna directory**
 * (367 places, `src/data/directory.ts`, generated by
 * `node scripts/build-directory.js`). This module layers the app's editorial
 * surfaces (featured hero, Discover collections, itinerary, events, filter
 * chips, "facts") on top of that catalog, always referencing real slugs so the
 * whole app stays in sync with the data.
 */

import { DIRECTORY, DIRECTORY_CATEGORIES } from './directory';

export const ICON_PATHS = {
  coffee: 'M17 8h1a4 4 0 1 1 0 8h-1M3 8h14v9a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4Z M5 2v2M9 2v2M13 2v2',
  nav: 'm3 11 19-9-9 19-2-8-8-2z',
  home: 'm3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z M9 22V12h6v10',
  waves:
    'M2 6c.6.5 1.2 1 2.5 1C7 7 7 5 9.5 5s2.4 2 5 2c1.3 0 1.9-.5 2.5-1 M2 12c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2s2.4 2 5 2c1.3 0 1.9-.5 2.5-1 M2 18c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2s2.4 2 5 2c1.3 0 1.9-.5 2.5-1',
  cal: 'M8 2v4M16 2v4M3 10h18 M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2z',
  clock: 'M12 7v5l3 3 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',
  peso: 'M7 3v18 M7 3h6a4 4 0 0 1 0 8H7 M4 9h12 M4 13h12',
  sun: 'M12 3v2M12 19v2M5 12H3M21 12h-2M18.4 5.6l-1.4 1.4M7 17l-1.4 1.4M17 17l1.4 1.4M5.6 5.6 7 7 M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',
  pin: 'M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0z M14 10a2 2 0 1 1-4 0 2 2 0 0 1 4 0',
  star: 'm12 2 2.9 6.3 6.9.7-5.1 4.6 1.4 6.8L12 17.6 5.9 20.4l1.4-6.8L2.2 9l6.9-.7z',
  message: 'M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z',
} as const;

export type Category = 'eat' | 'tour' | 'stay' | 'beach' | 'events';

export function catPath(c: Category): string {
  return c === 'eat'
    ? ICON_PATHS.coffee
    : c === 'tour'
      ? ICON_PATHS.nav
      : c === 'stay'
        ? ICON_PATHS.home
        : c === 'beach'
          ? ICON_PATHS.waves
          : ICON_PATHS.cal;
}

export type Place = {
  id: string;
  name: string;
  area: string;
  cat: Category;
  catLabel: string;
  /** Short chip label for the full (12-way) category. */
  catShort?: string;
  tint: string;
  /** Cover photo. Empty for directory places → PhotoBlock renders the tinted hatch. */
  image: string;
  tags: string[];
  price: string;
  priceLabel: string;
  hours: string;
  best: string;
  travel: string;
  openNow: boolean;
  blurb: string;

  // ── Directory extras (real Google Places data) ──────────────────────────
  /** True GPS latitude — projected on the offline Map screen. */
  lat?: number;
  /** True GPS longitude — projected on the offline Map screen. */
  lng?: number;
  rating?: number;
  reviews?: number;
  phone?: string;
  address?: string;
  /** Google Maps place page (photos + full reviews). */
  mapsUrl?: string;
  /** Google Maps turn-by-turn directions deep link. */
  dirsUrl?: string;
  placeId?: string;
  /** Full 12-way category label. */
  category?: string;
};

/** Build a sized, format-optimized Unsplash URL from a photo id. */
export function unsplash(id: string, w = 800): string {
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=70`;
}

/** Every place, in the compiled directory order. */
export const ALL_PLACES: Place[] = DIRECTORY;

/** The catalog keyed by slug. */
export const PLACES: Record<string, Place> = Object.fromEntries(
  DIRECTORY.map((p) => [p.id, p]),
);

export const PLACE_IDS = Object.keys(PLACES);

// ── Editorial helpers — always resolve to real slugs ────────────────────────

const fmtInt = (n: number) => n.toLocaleString('en-US');

/** Rank by rating weighted by (log) review volume, so busy + loved wins. */
function score(p: Place): number {
  return (p.rating ?? 0) * Math.log10((p.reviews ?? 0) + 10);
}
function inCats(labels: string[]): Place[] {
  return DIRECTORY.filter((p) => labels.includes(p.category ?? ''));
}
function topBy(arr: Place[], n: number): string[] {
  return [...arr].sort((a, b) => score(b) - score(a)).slice(0, n).map((p) => p.id);
}

/** Iconic featured spot for the Discover hero. */
export const FEATURED_ID: string =
  PLACES['cloud-9-surfing-area']?.id ?? topBy(inCats(['Things To Do']), 1)[0] ?? PLACE_IDS[0];

export type Category2 = { key: Category; label: string; tint: string; path: string };
export const CATEGORIES: Category2[] = [
  { key: 'eat', label: 'Eat', tint: '#F2762E', path: ICON_PATHS.coffee },
  { key: 'tour', label: 'Do', tint: '#2F7A4F', path: ICON_PATHS.nav },
  { key: 'stay', label: 'Stay', tint: '#E84F5C', path: ICON_PATHS.home },
  { key: 'beach', label: 'Surf', tint: '#0E7C86', path: ICON_PATHS.waves },
  { key: 'events', label: 'Events', tint: '#0A5A62', path: ICON_PATHS.cal },
];

/** Explore category filter chips — "All" + the 12 real directory categories. */
export type CategoryFilter = { key: string; label: string; tint: string };
export const CATEGORY_FILTERS: CategoryFilter[] = [
  { key: 'all', label: 'All', tint: '#0E7C86' },
  ...DIRECTORY_CATEGORIES.map((c) => ({ key: c.label, label: c.short, tint: c.tint })),
];

export function placeInCategory(p: Place, key: string): boolean {
  return key === 'all' || (p.category ?? p.catLabel) === key;
}

export type EventItem = {
  id: string;
  name: string;
  venue: string;
  date: string;
  day: string;
  time: string;
  tag: string;
  tint: string;
  image: string;
  place?: string;
};

const bars = topBy(inCats(['Bars & Nightlife']), 2);
const eatery = topBy(inCats(['Local Eateries & BBQ', 'Restaurants & Cafés']), 1)[0];
const venue = (slug?: string) => (slug ? PLACES[slug]?.name ?? 'General Luna' : 'General Luna');
const venueTint = (slug?: string) => (slug ? PLACES[slug]?.tint ?? '#0E7C86' : '#0E7C86');

export const EVENTS: EventItem[] = [
  { id: 'surfcomp', name: 'Cloud 9 Dawn Surf Session', venue: venue(FEATURED_ID), date: 'SAT', day: '25', time: 'Sunrise', tag: 'Surf', tint: venueTint(FEATURED_ID), image: '', place: FEATURED_ID },
  { id: 'fullmoon', name: 'Full Moon Beach Party', venue: venue(bars[0]), date: 'WED', day: '29', time: '9 PM late', tag: 'Party', tint: venueTint(bars[0]), image: '', place: bars[0] },
  { id: 'reggae', name: 'Live Reggae Night', venue: venue(bars[1] ?? bars[0]), date: 'FRI', day: '31', time: '8 PM', tag: 'Music', tint: venueTint(bars[1] ?? bars[0]), image: '', place: bars[1] ?? bars[0] },
  { id: 'market', name: 'Saturday Night Market', venue: venue(eatery), date: 'SAT', day: '25', time: '5–10 PM', tag: 'Market', tint: venueTint(eatery), image: '', place: eatery },
];

export type Collection = { title: string; key: string; items: string[] };
export const COLLECTIONS: Collection[] = [
  { title: 'Top rated on the island', key: 'top', items: topBy(DIRECTORY.filter((p) => (p.reviews ?? 0) >= 100), 8) },
  { title: 'Where the surfers eat', key: 'eat', items: topBy(inCats(['Restaurants & Cafés', 'Local Eateries & BBQ']), 8) },
  { title: 'Surf & water sports', key: 'surf', items: topBy(inCats(['Surf & Water Sports']), 8) },
  { title: 'Where to stay', key: 'stay', items: topBy(inCats(['Hotels & Resorts', 'Hostels & Guesthouses']), 8) },
  { title: 'Things to do', key: 'do', items: topBy(inCats(['Things To Do']), 8) },
];

export type ItineraryItem = { placeId: string; timeLabel: string; path: string };
export type ItineraryDay = { label: string; date: string; items: ItineraryItem[] };

const pick = (labels: string[], skip: Set<string>): string => {
  for (const id of topBy(inCats(labels), 12)) if (!skip.has(id)) { skip.add(id); return id; }
  return PLACE_IDS[0];
};
const used = new Set<string>();
export const ITINERARY: ItineraryDay[] = [
  {
    label: 'Day 1',
    date: 'Fri 20',
    items: [
      { placeId: pick(['Restaurants & Cafés'], used), timeLabel: '8:00 · Breakfast', path: ICON_PATHS.coffee },
      { placeId: FEATURED_ID, timeLabel: '10:00 · Surf check', path: ICON_PATHS.waves },
      { placeId: pick(['Bars & Nightlife', 'Restaurants & Cafés'], used), timeLabel: '17:30 · Sunset & drinks', path: ICON_PATHS.coffee },
    ],
  },
  {
    label: 'Day 2',
    date: 'Sat 21',
    items: [
      { placeId: pick(['Things To Do'], used), timeLabel: '07:30 · Island trip', path: ICON_PATHS.nav },
      { placeId: pick(['Things To Do'], used), timeLabel: '14:00 · Explore', path: ICON_PATHS.nav },
      { placeId: pick(['Wellness & Spas'], used), timeLabel: '18:00 · Massage', path: ICON_PATHS.sun },
    ],
  },
];

/** Popular / recent search suggestions (real, searchable terms). */
export const POPULAR = ['Las Barricas', 'tapas', 'Cloud 9', 'coffee', 'surf', 'massage'];
export const RECENTS = ['pizza', 'Naked Island', 'hostel'];

export const EVENT_CHIPS = ['This week', 'Weekend', 'Music', 'Markets', 'Surf', 'Parties'];

export const TIP_BANK: Record<string, string[]> = {
  default: [
    'Bring cash — many spots are card-free',
    'A habal-habal from General Luna runs ~₱150',
    'Download the offline map before you ride out',
  ],
};

/** Detail-screen "facts" strip, built from the real directory fields. */
export function placeFacts(p: Place) {
  return [
    { path: ICON_PATHS.star, label: 'Rating', value: p.rating ? `★ ${p.rating.toFixed(1)}` : 'New' },
    { path: ICON_PATHS.clock, label: 'Hours', value: p.hours },
    { path: catPath(p.cat), label: 'Category', value: p.catShort ?? p.catLabel },
    { path: ICON_PATHS.pin, label: 'Area', value: p.area },
    { path: ICON_PATHS.message, label: 'Reviews', value: p.reviews ? fmtInt(p.reviews) : '—' },
  ];
}

/** Build a "Good to know" list from a place's real details. */
export function placeTips(p: Place): string[] {
  const tips: string[] = [];
  if (p.rating) tips.push(`Rated ★ ${p.rating.toFixed(1)}${p.reviews ? ` from ${fmtInt(p.reviews)} reviews` : ''}`);
  if (p.hours && p.hours !== 'Hours vary') tips.push(`Hours: ${p.hours}`);
  if (p.address) tips.push(p.address);
  if (p.phone) tips.push(`Call or WhatsApp: ${p.phone}`);
  tips.push('Hours, prices and ATM availability change often — verify locally.');
  return tips;
}
